#!/bin/bash

TOPDIR=./
BETA=1.0
TMAX=1000
NUM_OF_SAVE_TIMES=100
QUARTILE_START=50
QUARTILE_STOP=4500
QUARTILE_STEP=50
SLURM_ARRAY_TASK_ID=1

python3 ../runFiles/RecurrenceDriver.py $TOPDIR $SLURM_ARRAY_TASK_ID $BETA $TMAX $NUM_OF_SAVE_TIMES $QUARTILE_START $QUARTILE_STOP $QUARTILE_STEP

pytest testRecurrenceDriverCleanUp.py
